os:
  - Visual Studio 2015
  - Visual Studio 2017

platform:
  - x64

services:
  - mysql

configuration:
  #- Debug
  - Release

matrix:
  fast_finish: true

build_script:
  - SET PATH=%PATH%;C:\Program Files\MySQL\MySQL Server 5.7\bin
  - set MYSQL_PWD=Password12!
  - SET
  - mysql -e "create database sqlpp_mysql;" --user=root
  - CD
  - echo %configuration%
  - mkdir build
  - cd build
  - cmake --version
  - cmake .. -DMYSQL_CONNECTOR=ON -DCMAKE_CXX_FLAGS="/EHsc /wd4503" -DCMAKE_PREFIX_PATH="C:\projects\date"
  - cmake --build . --config %configuration%
  - ctest . --build-config %configuration%
