language: cpp

os:
  - linux

dist: focal
sudo: required

services:
  - mysql

addons:
  apt:
    packages:
    - sqlite3
    - libboost-dev
    - python-pyparsing

compiler:
  - clang
  - gcc

env:
  - CONFIG=Release
  - CONFIG=Release TESTS_CXX_STD=17
  #- CONFIG=Debug

notifications:
 email:
   on_success: change
   on_failure: always

before_script:
   - mysql --version
   - (while !  mysqladmin -u root status ; do sleep 1; done) # wait for mysql to start
   - mysqladmin -u root create sqlpp_mysql
   - mkdir build
   - cd build
   - if [[ "$CXX" = "g++" && "$CONFIG" = "Debug" && "$TRAVIS_OS_NAME" = "linux" ]]; then export CXXFLAGS="--coverage"; fi
   - echo $ADD_OPTS
   - pwd
   - cmake .. \
     -DCMAKE_BUILD_TYPE=$CONFIG \
     -DMYSQL_CONNECTOR=ON \
     -DSQLITE3_CONNECTOR=ON \
     $ADD_OPTS

script:
   - cmake --build . --config $CONFIG
   - ctest --output-on-failure

after_script:
  - ../coveralls
